services:
  local-dope-wars:
    container_name: local-dope-wars
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/}
    image: local-dope-wars:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - ai-backend

networks:
  ai-backend:
    external: true
